"""Alembic migration smoke + drift tests.

These run via the Alembic Python API against a throwaway on-disk SQLite database
so they never touch the real ``finsight.db``. They assert that:

* the Alembic configuration loads and exposes a non-empty version history;
* applying ``upgrade head`` followed by ``alembic check`` yields no diff, i.e.
  the migrations are in sync with the current SQLAlchemy models.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic.command import check, upgrade
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected

BACKEND_ROOT = Path(__file__).resolve().parent.parent


def _make_config(database_url: str) -> Config:
    cfg = Config(str(BACKEND_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    cfg.set_main_option("sqlalchemy.url", database_url)
    return cfg


def test_alembic_config_loads_with_revisions() -> None:
    cfg = _make_config("sqlite://")
    script = ScriptDirectory.from_config(cfg)
    revisions = list(script.walk_revisions())
    assert revisions, "expected at least one migration revision"
    assert script.get_current_head() is not None


def test_migrations_match_models(tmp_path: Path) -> None:
    db_path = tmp_path / "migrations_check.db"
    cfg = _make_config(f"sqlite:///{db_path}")

    # Apply every migration to a fresh database...
    upgrade(cfg, "head")

    # ...then assert autogenerate finds no remaining difference vs the models.
    try:
        check(cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"alembic check detected model/migration drift: {exc}")
