/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Companies
         * @description Return all companies ordered by name.
         */
        get: operations["list_companies_api_companies_get"];
        put?: never;
        /**
         * Create Company
         * @description Create a new company record.
         */
        post: operations["create_company_api_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Company
         * @description Return a company with its associated period summaries.
         */
        get: operations["get_company_api_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/ratios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Company Ratios
         * @description Compute ratios for every period belonging to the company.
         *
         *     Returns a time-series suitable for trend charts. Valuation ratios that require
         *     market data will be ``unavailable`` here — use GET /periods/{id}/ratios with
         *     query params for those.
         */
        get: operations["get_company_ratios_api_companies__company_id__ratios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description Return all documents ordered newest-first.
         */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Accept a PDF upload and queue the extraction pipeline.
         *
         *     Stores the file on disk, creates a ``Document`` row, and schedules the
         *     extraction pipeline as a background task.
         *
         *     Returns HTTP 202 (Accepted) immediately; the client polls
         *     GET /documents/{id} to watch ``status`` transition through the pipeline stages:
         *         uploaded → parsing → extracting → needs_review | ready | failed
         */
        post: operations["upload_document_api_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Return a document with its associated period and line items.
         */
        get: operations["get_document_api_documents__doc_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Hard-delete a document record (does NOT remove the file from disk).
         */
        delete: operations["delete_document_api_documents__doc_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reprocess Document
         * @description Reset the document to 'uploaded' status and re-run the extraction pipeline.
         *
         *     Useful after the user has corrected OCR settings or the provider configuration
         *     has changed.
         */
        post: operations["reprocess_document_api_documents__doc_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return service health and the active LLM provider.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Period
         * @description Manually create a blank period (no documents attached yet).
         *
         *     Useful for entering historical data manually via the review UI before any
         *     document has been uploaded.
         */
        post: operations["create_period_api_periods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/periods/{period_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Period
         * @description Return a single period with its full canonical items and provenance.
         */
        get: operations["get_period_api_periods__period_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/periods/{period_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Period Items
         * @description Apply human corrections to individual line items.
         *
         *     Each key in ``updates`` is a canonical field name; the value is the new
         *     number (or ``null`` to clear it).  Touched entries are flagged
         *     ``edited_by_user=true`` so provenance is preserved.
         *
         *     Delegates to ``app.extraction.service.apply_item_updates`` which owns the
         *     merge logic so the pipeline and the review UI stay in sync.
         */
        patch: operations["patch_period_items_api_periods__period_id__items_patch"];
        trace?: never;
    };
    "/api/periods/{period_id}/ratios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Period Ratios
         * @description Compute all financial ratios for the given period.
         *
         *     Ratios are computed deterministically from the stored canonical line items —
         *     never by an LLM.  Each result carries a ``status``:
         *     - ``ok``          — value computed successfully
         *     - ``unavailable`` — one or more required inputs were missing
         *     - ``undefined``   — math is undefined (e.g. division by zero)
         *
         *     Pass ``market_price`` and/or ``shares_outstanding`` to unlock valuation
         *     ratios (P/E, EV/EBITDA, etc.).  Omitting them leaves those ratios as
         *     ``unavailable`` rather than erroring.
         */
        get: operations["get_period_ratios_api_periods__period_id__ratios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/periods/{period_id}/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Period Validation
         * @description Run deterministic accounting-identity checks for the given period.
         *
         *     Verifies accounting equations (assets = liabilities + equity, subtotals foot to
         *     totals, gross_profit = revenue - COGS, etc.) within a rounding tolerance. Each
         *     result carries a ``status``:
         *     - ``ok``          — the identity holds within tolerance
         *     - ``mismatch``    — the figures do not reconcile (likely an extraction error)
         *     - ``unavailable`` — one or more required line items were not reported
         *
         *     Like ratios, these are computed in pure Python, never by an LLM, so the UI can
         *     flag inconsistent extractions instead of trusting bad data silently.
         */
        get: operations["get_period_validation_api_periods__period_id__validation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_documents_upload_post */
        Body_upload_document_api_documents_upload_post: {
            /** Company Id */
            company_id?: number | null;
            /** File */
            file: string;
        };
        /**
         * CompanyDetailOut
         * @description Mirrors TS interface CompanyDetail — includes period summaries.
         */
        CompanyDetailOut: {
            /** Currency */
            currency: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Periods */
            periods: components["schemas"]["PeriodSummaryOut"][];
            /** Ticker */
            ticker: string | null;
        };
        /**
         * CompanyOut
         * @description Mirrors TS interface Company.
         */
        CompanyOut: {
            /** Currency */
            currency: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string | null;
        };
        /**
         * CompanyRatioTrendOut
         * @description Response body for GET /companies/{id}/ratios.
         */
        CompanyRatioTrendOut: {
            /** Periods */
            periods: components["schemas"]["PeriodRatiosOut"][];
        };
        /**
         * CreateCompanyIn
         * @description Request body for creating a company.
         */
        CreateCompanyIn: {
            /** Currency */
            currency?: string | null;
            /** Name */
            name: string;
            /** Ticker */
            ticker?: string | null;
        };
        /**
         * CreatePeriodIn
         * @description Request body for creating a financial period.
         */
        CreatePeriodIn: {
            /** Company Id */
            company_id: number;
            /** Fiscal Period End */
            fiscal_period_end?: string | null;
            /** Fiscal Year */
            fiscal_year?: number | null;
            /** Period Type */
            period_type?: string | null;
        };
        /**
         * DocumentDetailOut
         * @description Mirrors TS interface DocumentDetail — adds the associated period.
         */
        DocumentDetailOut: {
            /** Created At */
            created_at: string;
            /** Detected Statement Types */
            detected_statement_types: string[] | null;
            /** Error */
            error: string | null;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Num Pages */
            num_pages: number | null;
            period: components["schemas"]["PeriodDetailOut"] | null;
            /** Period Id */
            period_id: number | null;
            /** Status */
            status: string;
        };
        /**
         * DocumentOut
         * @description Mirrors TS interface Document.
         */
        DocumentOut: {
            /** Created At */
            created_at: string;
            /** Detected Statement Types */
            detected_statement_types: string[] | null;
            /** Error */
            error: string | null;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Num Pages */
            num_pages: number | null;
            /** Period Id */
            period_id: number | null;
            /** Status */
            status: string;
        };
        /**
         * FinancialValueOut
         * @description Mirrors TS interface FinancialValue.
         */
        FinancialValueOut: {
            /** Confidence */
            confidence: number | null;
            /** Edited By User */
            edited_by_user: boolean;
            /** Source Label */
            source_label: string | null;
            /** Source Page */
            source_page: number | null;
            /** Value */
            value: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityResultOut
         * @description One accounting-identity check result (mirrors validation.IdentityResult).
         */
        IdentityResultOut: {
            /** Detail */
            detail: string | null;
            /** Difference */
            difference: number | null;
            /** Key */
            key: string;
            /** Lhs */
            lhs: number | null;
            /** Missing Inputs */
            missing_inputs: string[];
            /** Name */
            name: string;
            /** Rhs */
            rhs: number | null;
            /** Status */
            status: string;
            /** Tolerance */
            tolerance: number | null;
        };
        /**
         * OkOut
         * @description Generic success response body.
         */
        OkOut: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /**
         * PatchItemsIn
         * @description Body for PATCH /periods/{period_id}/items.
         */
        PatchItemsIn: {
            /** Updates */
            updates: {
                [key: string]: number | null;
            };
        };
        /**
         * PeriodDetailOut
         * @description Mirrors TS interface PeriodDetail — full canonical items with provenance.
         */
        PeriodDetailOut: {
            /** Company Id */
            company_id: number;
            /** Company Name */
            company_name: string | null;
            /** Currency */
            currency: string | null;
            /** Fiscal Period End */
            fiscal_period_end: string | null;
            /** Fiscal Year */
            fiscal_year: number | null;
            /** Id */
            id: number;
            /** Items */
            items: {
                [key: string]: components["schemas"]["FinancialValueOut"];
            };
            /** Period Type */
            period_type: string | null;
        };
        /**
         * PeriodRatiosOut
         * @description Mirrors TS interface PeriodRatios — one period + its ratio results.
         */
        PeriodRatiosOut: {
            period: components["schemas"]["PeriodSummaryOut"];
            /** Results */
            results: components["schemas"]["RatioResultOut"][];
        };
        /**
         * PeriodSummaryOut
         * @description Mirrors TS interface PeriodSummary — lightweight, used in list responses.
         */
        PeriodSummaryOut: {
            /** Fiscal Period End */
            fiscal_period_end: string | null;
            /** Fiscal Year */
            fiscal_year: number | null;
            /** Id */
            id: number;
            /** Period Type */
            period_type: string | null;
        };
        /**
         * RatioReportOut
         * @description Mirrors TS interface RatioReport.
         */
        RatioReportOut: {
            /** Period Id */
            period_id: number;
            /** Results */
            results: components["schemas"]["RatioResultOut"][];
        };
        /**
         * RatioResultOut
         * @description Mirrors TS interface RatioResult.
         */
        RatioResultOut: {
            /** Category */
            category: string;
            /** Detail */
            detail: string | null;
            /** Key */
            key: string;
            /** Missing Inputs */
            missing_inputs: string[];
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationReportOut
         * @description Accounting-identity validation for a single period.
         */
        ValidationReportOut: {
            /** Period Id */
            period_id: number;
            /** Results */
            results: components["schemas"]["IdentityResultOut"][];
            /** Summary */
            summary: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_companies_api_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
        };
    };
    create_company_api_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompanyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_ratios_api_companies__company_id__ratios_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRatioTrendOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    upload_document_api_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_document_api_documents__doc_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_period_api_periods_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePeriodIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_period_api_periods__period_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                period_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_period_items_api_periods__period_id__items_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                period_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchItemsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_period_ratios_api_periods__period_id__ratios_get: {
        parameters: {
            query?: {
                /** @description Current share price in reporting currency. Required for valuation ratios. */
                market_price?: number | null;
                /** @description Shares outstanding (absolute count, not millions). Required for market-cap-based valuation ratios. Falls back to the value extracted from the income statement when absent. */
                shares_outstanding?: number | null;
            };
            header?: never;
            path: {
                period_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatioReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_period_validation_api_periods__period_id__validation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                period_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
