#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# finsight quickstart — one command, NO API keys required.
#
# Brings up the whole app locally with a key-free local LLM (Ollama in Docker):
#   postgres + backend (FastAPI) + frontend (nginx SPA) + ollama + model pull.
#
# The only prerequisite is Docker (with the Compose plugin). Everything else —
# the database, the LLM, the model download — is handled for you.
#
# Usage:
#   ./scripts/quickstart.sh           # build + start everything, then print the URL
#   LLM_MODEL=llama3.1 ./scripts/quickstart.sh   # use a larger/better model
#
# Stop it later with:  docker compose --profile local-llm down
# Wipe all data with:  docker compose --profile local-llm down -v
# ---------------------------------------------------------------------------
set -euo pipefail

cd "$(dirname "$0")/.."

FRONTEND_PORT="${FRONTEND_PORT:-3000}"
LLM_MODEL="${LLM_MODEL:-llama3.2:3b}"
ENV_FILE=".env"
COMPOSE=(docker compose --profile local-llm)

say() { printf '\033[36m▶ %s\033[0m\n' "$*"; }
die() {
  printf '\033[31m✗ %s\033[0m\n' "$*" >&2
  exit 1
}

# --- 0. prerequisites ------------------------------------------------------
command -v docker >/dev/null 2>&1 || die "Docker is required. Install Docker Desktop: https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || die "The Docker Compose plugin is required (try a newer Docker Desktop)."
docker info >/dev/null 2>&1 || die "Docker is installed but not running — start Docker and re-run."

# --- 1. generate a .env if absent (no secrets to supply) -------------------
if [ ! -f "$ENV_FILE" ]; then
  say "Creating $ENV_FILE (local, key-free defaults)"
  if command -v openssl >/dev/null 2>&1; then
    pg_pw="$(openssl rand -hex 16)"
  else
    pg_pw="finsight_local_dev"
  fi
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/quickstart.sh — local, key-free setup.
POSTGRES_PASSWORD=${pg_pw}
FRONTEND_PORT=${FRONTEND_PORT}

# Local LLM via Ollama — NO API key needed.
LLM_PROVIDER=ollama
LLM_MODEL=${LLM_MODEL}
OLLAMA_BASE_URL=http://ollama:11434
EOF
else
  say "Using existing $ENV_FILE (leaving it as-is)"
fi

# --- 2. build + start the stack -------------------------------------------
say "Building and starting the stack (this is slow the first time)…"
LLM_MODEL="$LLM_MODEL" "${COMPOSE[@]}" up -d --build

# --- 3. pull the model (ollama-init) --------------------------------------
say "Pulling the local model '${LLM_MODEL}' (first run downloads ~2 GB)…"
# ollama-init is a one-shot puller started by `up`. Block until it exits (its
# stdout format varies by compose version, so read the true exit code from the
# container rather than parsing the message). This does not stop the services.
LLM_MODEL="$LLM_MODEL" "${COMPOSE[@]}" wait ollama-init >/dev/null 2>&1 || true
init_cid="$("${COMPOSE[@]}" ps -aq ollama-init 2>/dev/null | head -1)"
code="$(docker inspect -f '{{.State.ExitCode}}' "$init_cid" 2>/dev/null || echo 1)"
if [ "$code" != "0" ]; then
  "${COMPOSE[@]}" logs ollama-init | tail -20 || true
  die "Model pull failed (exit ${code}). Check 'docker compose --profile local-llm logs ollama'."
fi

# --- 4. wait for the app to answer ----------------------------------------
say "Waiting for the app to become healthy…"
base="http://localhost:${FRONTEND_PORT}"
for _ in $(seq 1 60); do
  if curl -fsS "${base}/api/health" >/dev/null 2>&1; then
    ok=1
    break
  fi
  sleep 2
done
[ "${ok:-}" = 1 ] || die "App did not become healthy in time. See 'docker compose --profile local-llm logs'."

# --- 5. done ---------------------------------------------------------------
cat <<EOF

✅ finsight is running — no API keys needed.

   Open:        ${base}
   Health:      ${base}/api/health
   LLM:         Ollama (local) · model '${LLM_MODEL}'

   Logs:        docker compose --profile local-llm logs -f
   Stop:        docker compose --profile local-llm down
   Reset all:   docker compose --profile local-llm down -v
EOF
